name: Distribute

on:
  push:
    branches: [ main ]
    
jobs:

  # Build ios app.
  build_ios:
    runs-on: macos-latest
    timeout-minutes: 40

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Cache Pods
        uses: actions/cache@v2
        with:
          path: ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Set up flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Set up GoogleService-info.plist
        run: |
          echo "${{ secrets.GOOGLE_SERVICE_INFO_PLIST_BASE64 }}" > GoogleService-Info.plist.txt
          base64 --decode GoogleService-Info.plist.txt > app/ios/Runner/GoogleService-Info.plist

      - name: Set up provisioning profile
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          echo "${{ secrets.IOS_PROVISIONING_PROFILE_BASE64 }}" > development.mobileprovision.txt
          base64 --decode development.mobileprovision.txt > ~/Library/MobileDevice/Provisioning\ Profiles/CREPE_iOS_Development.mobileprovision

      - name: Set up certificate
        uses: Apple-Actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.IOS_CERTIFICATE_BASE64 }}
          p12-password: ${{ secrets.IOS_CERTIFICATE_PASSWORD }}

      - name: Install dependency packages
        run: | 
          cd packages/crepe_core
          flutter pub get
          cd ..
          cd crepe_ui
          cd ../..
          cd app
          flutter pub get

      - name: Build ipa file
        run: | 
          cd app
          flutter build ipa --export-options-plist=ios/ExportOptions.plist --build-number ${GITHUB_RUN_NUMBER}

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ios
          path: app/build/ios/ipa/Crepe.ipa

  # Build android app.
  build_android:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up JDK 8.x
        uses: actions/setup-java@v1
        with:
          java-version: '8.x'

      - name: Set up flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Set up google-service.json
        run: |
          cd app/android/app
          echo "${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}" > google-services.json.txt
          base64 --decode google-services.json.txt > google-services.json
          cd ../../../
      
      - name: Set up keystore
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" > release.jks.txt
          base64 --decode release.jks.txt > app/release.jks

      - name: Install dependency packages
        run: | 
          cd packages/crepe_core
          flutter pub get
          cd ..
          cd crepe_ui
          cd ../..
          cd app
          flutter pub get

      - name: Build apk file
        run: |
          export KEYSTORE_PASSWORD='${{ secrets.ANDROID_KEYSTORE_PASSWORD }}'
          export KEY_ALIAS='${{ secrets.ANDROID_KEY_ALIAS }}'
          export KEY_PASSWORD='${{ secrets.ANDROID_KEYSTORE_PASSWORD }}'
          cd app
          flutter build apk --release --build-number ${GITHUB_RUN_NUMBER}

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: android
          path: build/app/outputs/flutter-apk/app-release.apk